name: Action for analyzing current version
description: Gets current version and analyzes it

outputs:
    version:
        description: Exact version
    isPrerelease:
        description: Is prerelease version
    releaseTag:
        description: Release tag

runs:
    using: node16
    main: ./index.js
