name: Pull Request
description: Submit a pull request for review.
title: '[PR] <title>'

body:
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issue(s)
      description: |
        List all related issues this PR addresses.  
        Use the full syntax (`closes #issue-number`) for each issue so they are automatically closed on merge.  
        Example: `closes #0001, closes #0002`
      placeholder: closes #0001, closes #0002
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Enter a short description of the change.
      placeholder: Briefly describe what this PR changes.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Screenshots

        If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.

  - type: input
    id: screenshot-before
    attributes:
      label: Screenshot - Before
      description: Upload or link to a screenshot showing the previous state (if applicable).
      placeholder: Drag & drop or paste image/link here
    validations:
      required: false

  - type: input
    id: screenshot-after
    attributes:
      label: Screenshot - After
      description: Upload or link to a screenshot showing the new state (if applicable).
      placeholder: Drag & drop or paste image/link here
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Implementation Checklist

        Please check all that apply during implementation and review.

  - type: checkboxes
    id: visual-testing
    attributes:
      label: Visual Testing
      description: Ensure the following visual aspects are validated.
      options:
        - label: No visual misalignments or unexpected updates
        - label: Checked in Light, Dark, HCB, and HCW themes
        - label: RTL and LTR rendering and labeling
        - label: Responsive (resize tested)
        - label: Content Density (Cozy, Compact, Condensed)
        - label: All states (hover, disabled, focused, active, on click, selected, selected hover, press state)
        - label: Interaction/Animation (open/close, expand/collapse, add/remove, check/uncheck)
        - label: Mouse and keyboard support
        - label: Text truncation handled

  - type: checkboxes
    id: api-functional
    attributes:
      label: API and Functional Correctness
      description: Ensure the following API and functional aspects are validated.
      options:
        - label: No console warnings or errors
        - label: API boundary values tested
        - label: Different combinations of components tested (free style)
        - label: API values changed during testing

  - type: checkboxes
    id: documentation-examples
    attributes:
      label: Documentation and Example Validation
      description: Ensure documentation and examples are complete and clear.
      options:
        - label: API documentation is complete and understandable
        - label: Examples are comprehensive and clear
        - label: Stackblitz works for all examples

  - type: checkboxes
    id: accessibility
    attributes:
      label: Accessibility Testing
      description: Ensure accessibility (a11y) is validated.
      options:
        - label: Accessibility testing completed

  - type: checkboxes
    id: browser-testing
    attributes:
      label: Browser Testing
      description: Test in all supported browsers.
      options:
        - label: Edge
        - label: Safari
        - label: Chrome
        - label: Firefox

  - type: markdown
    attributes:
      value: |
        ## PR Quality Checklist

  - type: checkboxes
    id: pr-quality
    attributes:
      label: PR Quality
      description: Ensure the following quality checks are completed.
      options:
        - label: Commit message(s) follow the [guideline](https://github.com/SAP/ui5-webcomponents-ngx/blob/main/CONTRIBUTING.md)
        - label: Tests are included for the changes
        - label: All items on the [PR Review Checklist](https://github.com/SAP/ui5-webcomponents-ngx/wiki/PR-Review-Checklist) are addressed
        - label: Ran `npm run build-pack-library` and tested in an external application
        - label: see `README.md` and updated if needed
        - label: [Breaking Changes Wiki](https://github.com/SAP/ui5-webcomponents-ngx/wiki/Breaking-Changes) updated if applicable

  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: Add any other information, blockers, or notes for reviewers.
    validations:
      required: false