name: PR checks

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NX_BRANCH: ${{ github.event.number || github.ref_name }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup Node.js and Cache
          uses: ./.github/actions/nodejs
        - name: Sync
          run: npx nx run-many --target=sync --all
        - name: Test
          run: npx nx run-many --target=test --all
        - name: Run build
          run: npx nx run-many --target=build --all
